version:  2.0
jobs:
  build:
    docker:
      - image: gradle:jdk11
    steps:
      - checkout
      - run:
          name: Build App v4
          command: |
                ci/build-app.sh
      - store_test_results:
                path: test-results
